# Copyright (c) 2010-2024, Lawrence Livermore National Security, LLC. Produced
# at the Lawrence Livermore National Laboratory. All Rights reserved. See files
# LICENSE and NOTICE for details. LLNL-CODE-806117.
#
# This file is part of the MFEM library. For more information and source code
# availability visit https://mfem.org.
#
# MFEM is free software; you can redistribute it and/or modify it under the
# terms of the BSD-3 license. We welcome feedback and contributions, see file
# CONTRIBUTING.md for details.

# Resources:
# - (source repo) Syntax for curl POST command that triggers a workflow dispatch event
#   - https://docs.github.com/en/rest/actions/workflows?apiVersion=2022-11-28#create-a-workflow-dispatch-event
#   - https://github.com/orgs/community/discussions/26323#discussioncomment-3251448
# - (target repo) Payload for the workflow dispatch event
#   - https://docs.github.com/en/webhooks/webhook-events-and-payloads#workflow_dispatch


name: trigger-pymfem

inputs:
  target-workflow:
    description: 'Name of the PyMFEM workflow to trigger'
    required: true
    default: 'build-and-test'
  source-branch:
    description: 'MFEM branch to use for the PyMFEM workflow'
    required: true
    default: 'master'

runs:
  using:
  steps:
    - name: Send POST request to PyMFEM via curl
      run: |
        curl -L \
             -X POST \
             -H "Accept: application/vnd.github+json" \
             -H "Authorization: Bearer ${{ secrets.PAT }}" \
             -H "X-GitHub-Api-Version: 2022-11-28" \
             https://api.github.com/repos/mfem/pymfem/actions/workflows/${{ inputs.target-workflow }}.yml/dispatches \
             -d '{"ref": "${{ inputs.source-branch }}", "inputs":{}}'
