# Copyright (c) 2010-2021, Lawrence Livermore National Security, LLC. Produced
# at the Lawrence Livermore National Laboratory. All Rights reserved. See files
# LICENSE and NOTICE for details. LLNL-CODE-806117.
#
# This file is part of the MFEM library. For more information and source code
# availability visit https://mfem.org.
#
# MFEM is free software; you can redistribute it and/or modify it under the
# terms of the BSD-3 license. We welcome feedback and contributions, see file
# CONTRIBUTING.md for details.

name: build-hypre

inputs:
  url:
    description: 'URL where to look for Hypre'
    required: false
    default: 'https://github.com/hypre-space/hypre/archive'
  archive:
    description: 'Archive to download'
    required: true
  dir:
    description: 'Hypre top directory name'
    required: true
  target:
    description: 'A key to identify the desired hypre config (int32, int64)'
    required: false
    default: int32

runs:
  using: "composite"
  steps:
    - name: Get Hypre (Windows)
      if: runner.os == 'Windows'
      run: |
        $URI_HYPRE = "${{ inputs.url }}/${{ inputs.archive }}"
        Invoke-WebRequest -Uri $URI_HYPRE -OutFile ${{ inputs.archive }}
        Remove-Item ${{ inputs.dir }} -Force -Recurse -ErrorAction Ignore;
        tar -xzf ${{ inputs.archive }};
      shell: pwsh

    - name: Get Hypre (Linux/macOS)
      if: runner.os != 'Windows'
      run: |
        wget --no-verbose ${{ inputs.url }}/${{ inputs.archive }};
        rm -rf ${{ inputs.dir }};
        tar -xzf ${{ inputs.archive }};
      shell: bash

    - name: Install Hypre
      run: |
        echo "Map target to options"
        if [[ "${{ inputs.target }}" == "int32" ]]
        then
          export hypre_options="";
        elif [[ "${{ inputs.target }}" == "int64" ]]
        then
          export hypre_options="-DHYPRE_ENABLE_BIGINT=ON";
        else
          echo "Hypre target not recognized";
          exit 1;
        fi
        echo "Installing Hypre"
        cd ${{ inputs.dir }};
        cmake -Hsrc -Bbuild \
          ${hypre_options} \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX=../install
        cmake --build build --config Release --parallel 3
        cmake --install build --config Release
        cd ../..;
      shell: bash
